apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 * * *" # Ejecutar a medianoche
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: tu-imagen-de-backup
            env:
            - name: DATABASE_URL
              value: "tu-url-de-base-de-datos"
            command: ["sh", "-c", "node /app/backup.js"]
          restartPolicy: OnFailure